### ISSUE TITLE
Problems reading files when developing in a localhost env ?

### ISSUE THREAD

**Issue by RemyCampanals** [flyimg/flyimg#330]
Hello flyimg team !

I'm trying to get working flyimg on two separate docker containers and i have the following error : 
```
Error occurred while trying to read the file Url :
```

Here's my docker configuration using your documentation and my configuration :
```
version: '3.8'

services:
 nginx:
    container_name: symbioze-nginx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'

  images:
    container_name: symbioze-images
    image: flyimg/flyimg-build
    ports:
      - '81:80'
```

I did nothing into my nginx configuration because i think it's not needed (?). But when i try to use 
```
http://localhost:81/upload/w_600,h_300,smc_1,q_90/https://www.symbioze.dev/uploads/pages/contents/destiny-2-warmind-622b6192d06bc.jpg
```
I can't get nothing but the error "can't read the file". 
I tried to debug a little, but it seems to be the Line: 93 at /var/www/html/src/Core/Entity/Image/InputImage.php who is throwing the error :
```php
if (!$stream = @fopen($this->sourceImageUlr, 'r', false, $context)) {
```
Any ideas ? :)

Thanks in advance
