### ISSUE TITLE
With many flyimg docker replicas, does it make sense to share the /tmp directory ? 

### ISSUE THREAD

**Issue by francescor** [flyimg/flyimg#495]
We have been using successfully flyimg in a Traefik/Docker swarm setup with 2+ replicas  (thanks!) 

So far we did not use S3 (we'll start now) and to easy the load we've so far been sharing the `/tmp` directory between replicas: the idea was that the job of one container can be somehow recycled by the other container (I guess at least the 'download' of the original...) 

This is the relevant part of the stack.yml file

```
...
    volumes:
      - /efs-directory/data/flyimg/tmp:/var/www/html/var/tmp
    environment:
      MAGICK_TMPDIR: /var/www/html/var/tmp      #mapped to filesystem
      MAGICK_THREAD_LIMIT: 8
      # Set maximum amount of memory map in bytes to allocate for the pixel cache. When this limit is exceeded, the image pixels are cached to disk (see MAGICK_DISK_LIMIT).
      MAGICK_MAP_LIMIT: '512MB'
      # Set maximum amount of memory in megabytes to allocate for the pixel cache from the heap. When this limit is exceeded, the image pixels are cached to memory-mapped disk (see MAGICK_MAP_LIMIT).
      MAGICK_MEMORY_LIMIT: '1024MB'
      MAGICK_WIDTH_LIMIT: '100MP'
      MAGICK_HEIGHT_LIMIT: '100MP'
```

btw: that shared dir ended up with over 100.000 files and over 50G, so I guess it's really too much

Now that we start using S3, does it make sense to still share that `/tmp` directory? (we'll enable the cron to empty it for sure now)
