### ISSUE TITLE
Add Watermarking with Text

### ISSUE THREAD

**Issue by sadok-f** [flyimg/flyimg#538]
Add Watermarking with Text.
possible options:

```yaml
  text: Hello!
  text-color: white
  text-size: 14
  text-bg: red
```

URL:
`upload/g_Center,tbg_red,t_Hello!,tc_white,ts_32/IMAGE_SOURCE_URL`
